language: node_js
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      script: npm run deploy
# deploy:
#   provider: script
#   script: deploy.sh
#   on:
#     all_branches: true
#     condition: $TRAVIS_BRANCH =~ ^staging|production$
